version: 2
jobs:
  credo:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get

      - run: mix credo

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

  format:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get

      - run: mix format --check-formatted

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

  test:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get

      - run: mix test --exclude network

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

  dialyzer:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get

      - run: mix dialyzer --plt

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix dialyzer --halt-exit-status

workflows:
  version: 2
  test:
    jobs:
      - credo
      - format
      - test
      - dialyzer
