version: 2
jobs:
  credo:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get

      - run: mix credo

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

  format:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get

      - run: mix format --check-formatted

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

  test:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest

    steps:
      - checkout
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run:
          name: mix test --exclude network --parallel --umbrella
          command: |
            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
              mix coveralls.html --exclude network --parallel --umbrella
            else
              mix coveralls.circle --exclude network --parallel --umbrella
            fi

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - store_artifacts:
          path: cover/excoveralls.html

  dialyzer:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get

      - run: mix dialyzer --plt

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix dialyzer --halt-exit-status

  release:
    working_directory: ~/ethereum
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: RELEASE_VERSION="0.1.0" mix release --verbose

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - store_artifacts:
          path: ~/ethereum/_build/releases/0.1.0/ethereum.tar.gz
          destination: releases

workflows:
  version: 2
  test:
    jobs:
      - credo
      - format
      - test
      - dialyzer
      - release
